version: '3'
services:
  front:
    container_name: umaishopfront
    command: bash -c "npm start && npm prestart"
    image: jimwinnie/umaishop-front:latest
    ports:
      - "4200:4200"
    environment:
      - URL_API=http://localhost:3000
      - URL_FRONT=http://localhost:4200
    labels:
      kompose.service.type: LoadBalancer

  api:
    container_name: umaishopapi
    command: nodemon -L server.js
    image: jimwinnie/umaishop-api:latest
    ports:
      - "3000:3000"
    environment:
      - URL_MONGO=mongodb://root:password@mongo
      - URL_API=http://localhost:3000
      - URL_FRONT=http://localhost:4200
      - SECRET_KEY=667877b49c1712be993161c057be1deea8444de1aba2ef13da9e27d2487574d2ad59c82d5fbf8a39df46ea939698fba42c84f22814819c3ff2091ab4e424e770
    depends_on:
      - mongo
    labels:
      kompose.service.type: LoadBalancer

  mongo:
    container_name: umaishopmongo
    image: mongo:latest
    volumes:
      - ../umaishopdb:/data/db
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    labels:
      kompose.service.type: LoadBalancer